export const POLICY = {
  RETIREMENT_AGE: 60,
  DIRECT_RETIREMENT_THRESHOLD_MONTHS: 18,
  MAX_MERGED_YEARS: 5,
  MAX_TOTAL_YEARS: 25,

  PERSONAL_DEDUCTION_RATE_ACTIVE: 0.33,
  PERSONAL_DEDUCTION_RATE_RETIRED: 0.25,

  REAL_ESTATE_CEILING_HIGH_SALARY: 0.65,
  REAL_ESTATE_CEILING_LOW_SALARY: 0.55,
  SALARY_CEILING_BREAKPOINT: 15000,

  // TODO: CONFIRM 17% WITH CEO before shipping. Flagged in README.
  PERSONAL_DISCOUNT_RATE: 0.17,

  PENSION_DIVISOR: 480,
} as const;
